name = "interaction18"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Interaction 18 Hugo theme."
homepage = "https://interaction18.ixda.org"
tags = ["Interaction", "ixda"]
min_version = 0.1

[author]
  name = "zufrieden"
  homepage = "https://github.com/zufrieden"
