baseURL = "https://interaction18.ixda.org/"
languageCode = "en-us"
DefaultContentLanguage = "en"

theme = "interaction18"
title = "Interaction 18 – 3—8 February 2018 • Lyon, France"
hrefTargetBlank = true

[params]
  partnersData = "https://script.google.com/macros/s/AKfycbxXn-yuUZevCgC484cyhQ-Wr6MDccEqvDvdzR6DlzkC3zfuT_8/exec?id=1I1tqSbAVRccL1N2yKQ3aiSzgNryLNzhfX6SAQ8xkNVI&sheet=partners"
  teamData = "https://script.google.com/macros/s/AKfycbxXn-yuUZevCgC484cyhQ-Wr6MDccEqvDvdzR6DlzkC3zfuT_8/exec?id=1j7GyZ2PuLtbZxM4ljLyFlLUadtYxxyMjWHW9bWnBuQY&sheet=team"
  programData = "https://script.google.com/macros/s/AKfycbxXn-yuUZevCgC484cyhQ-Wr6MDccEqvDvdzR6DlzkC3zfuT_8/exec?id=12JUQA4ogk1JGMlRtofFKJmn6NgCGMCCmtOqwqvChxT4&sheet=program"

[menu]
[[menu.main]]
    name = "Home"
    weight = 80
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about/"

 [[menu.about]]
 	parent = "about"

[[menu.main]]
    name = "Lyon"
    weight = 200
    identifier = "lyon"
    url = "/lyon/"

 [[menu.lyon]]
 	parent = "lyon"

[[menu.main]]
  name = "Venues & Events"
  weight = 300
  identifier = "venues"
  url = "/venues/"

[[menu.main]]
  name = "Program"
  weight = 450
  identifier = "program"
  url = "/program/"

 [[menu.program]]
  parent = "program"

[[menu.main]]
    name = "Partners"
    weight = 500
    identifier = "partners"
    url = "/partners/"


[Languages]
[Languages.en]
languageName = "EN"


[Languages.fr]
languageCode = "fr-fr"
languageName = "FR"
title = "Interaction 18 – 3—8 Février 2018 • Lyon, France"

[[Languages.fr.menu.main]]
    name = "Accueil"
    weight = 80
    identifier = "home"
    url = "/"

[[Languages.fr.menu.main]]
    name = "À propos"
    weight = 100
    identifier = "about"
    url = "/about/"

[[Languages.fr.menu.main]]
    name = "Lyon"
    weight = 200
    identifier = "lyon"
    url = "/lyon/"

[[Languages.fr.menu.main]]
  name = "Lieux"
  weight = 300
  identifier = "venues"
  url = "/venues/"

[[Languages.fr.menu.main]]
  name = "Workshops"
  weight = 450
  identifier = "program"
  url = "/program/"

[[Languages.fr.menu.main]]
  name = "Conférenciers"
  weight = 400
  identifier = "speakers"
  url = "/speakers/"

[[Languages.fr.menu.main]]
    name = "Partenaires"
    weight = 500
    identifier = "partners"
    url = "/partners/"
