baseURL = "http://interaction18.ixda.org/"
languageCode = "en-us"
theme = "interaction18"
title = "Interaction 18 – 3—8 February 2018 • Lyon, France"
hrefTargetBlank = true

[params]
  partnersData = "https://script.google.com/macros/s/AKfycbxOLElujQcy1-ZUer1KgEvK16gkTLUqYftApjNCM_IRTL3HSuDk/exec?id=1I1tqSbAVRccL1N2yKQ3aiSzgNryLNzhfX6SAQ8xkNVI&sheet=partners"
  teamData = "https://script.google.com/macros/s/AKfycbxOLElujQcy1-ZUer1KgEvK16gkTLUqYftApjNCM_IRTL3HSuDk/exec?id=1j7GyZ2PuLtbZxM4ljLyFlLUadtYxxyMjWHW9bWnBuQY&sheet=team"
  programData = "https://script.google.com/macros/s/AKfycbxOLElujQcy1-ZUer1KgEvK16gkTLUqYftApjNCM_IRTL3HSuDk/exec?id=12JUQA4ogk1JGMlRtofFKJmn6NgCGMCCmtOqwqvChxT4&sheet=program"

[menu]
[[menu.main]]
    name = "Home"
    weight = 80
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about/"

 [[menu.about]]
 	parent = "about"

[[menu.main]]
    name = "Lyon"
    weight = 200
    identifier = "lyon"
    url = "/lyon/"

 [[menu.lyon]]
 	parent = "lyon"

[[menu.main]]
  name = "Venues"
  weight = 300
  identifier = "venues"
  url = "/venues/"

[[menu.main]]
  name = "Speakers"
  weight = 400
  identifier = "speakers"
  url = "/speakers/"

[[menu.main]]
    name = "Partners"
    weight = 500
    identifier = "partners"
    url = "/partners/"
